### ISSUE TITLE
Error when build in travis-CI

### ISSUE THREAD

**Issue by zzau13** [atSistemas/angular-base#34]
**I want request a bug.**

**Current behavior**

When travis-ci do `ngc -p tsconfig.aot.json` can't find the correct webpack types definition.

**Expected behavior**

Done without errors.

**Relevant information such as the browser version, Node.js version, and Operating System.**
Your Travis-CI

**Comment by pmagaz** [comment]
Hi:

There aren't any errors in Travis or Appveyor. Please don't take logs of a feature branch and open a bug with it. 

Thanks.
