### ISSUE TITLE
Smarter change detection

### ISSUE THREAD

**Issue by zzau13** [atSistemas/angular-base#36]
**I want request a bug.**

**The current behavior is:**

44 view checks for click button, update or not the state, only in CalculatorComponent

![Logs](https://user-images.githubusercontent.com/2625545/38439714-0b5d6e3a-39df-11e8-8073-492db6eafb34.png)
![logs](https://user-images.githubusercontent.com/2625545/38439902-a55a29c4-39df-11e8-9a8a-bbb4683d22c9.jpg)

**Steps to reproduce:**

* Define 
```typescript
import { AfterViewChecked } from '@angular/core';

export class DebugViewCheck implements AfterViewChecked {
  ngAfterViewChecked(): void {
    console.log('[CHECK]', this.constructor.name);
  }
}
```
* Extends components with DebugViewCheck
* Count logs

**Expected behavior**

Check the view only when the component status changes, using [ChangeDetectionStrategy](https://angular.io/api/core/ChangeDetectionStrategy) and [ChangeDetectorRef](https://angular.io/api/core/ChangeDetectorRef). As described in [ngrx](https://github.com/ngrx/platform/blob/master/docs/store/README.md#ngrxstore) and explained [smarter-change-detection](https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html#smarter-change-detection)

**Relevant information such as the browser version, Node.js version, and Operating System.**
Linux 4.15.*, Node 8.9.4, Chromium 65

**Comment by pmagaz** [comment]
Hi:

Your behavior is not reproducible  as you can see in the log:

[BASE] DEVELOPMENT MODE
app.js:8605 [HMR] Waiting for update signal from WDS...
app.js:10831 action @ 11:29:35.852 @ngrx/effects/init (in 0.10 ms)
core.js:3660 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
app.js:10831 action @ 11:29:35.906 ROUTER_NAVIGATION (in 0.00 ms)
app.js:8262 [CHECK] CalculatorContainer
app.js:13342 [HMR] connected
app.js:10831 action @ 11:29:39.778 INPUT_NUMBER (in 0.20 ms)
app.js:8262 [CHECK] CalculatorContainer
app.js:10831 action @ 11:29:40.291 INPUT_OPERATOR (in 0.10 ms)
app.js:8262 [CHECK] CalculatorContainer
app.js:10831 action @ 11:29:41.097 INPUT_OPERATION (in 0.30 ms)
app.js:8262 [CHECK] CalculatorContainer
app.js:10831 action @ 11:29:51.299 INPUT_OPERATION (in 0.10 ms)
app.js:8262 [CHECK] CalculatorContainer
app.js:10831 action @ 11:29:51.821 INPUT_NUMBER (in 0.10 ms)
app.js:8262 [CHECK] CalculatorContainer

Closed for Trolling.

**Comment by zzau13** [comment]
Extends all your components inside CalculatorContainer, display, buttons...
